src/main/java/jp/co/elearning/form/LoginForm.java
package jp.co.elearning.form;

import java.util.Date;

import org.hibernate.validator.constraints.NotEmpty;


public class LoginForm {

	private Integer id;
	private String name;

	@NotEmpty(message = "アカウント名を入力してください")
	private String account;

	@NotEmpty(message = "パスワードを入力してください")
	private String password;

	private Integer divisionId;
	private Date created_date;
	private Date updated_date;
	private Integer progress;

	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
	    this.id = id;
	}
	public String getName() {
	     return name;
	}
	public void setName(String name) {
	     this.name = name;
	}
	public String getPassword() {
	     return password;
	}
	public void setPassword(String password) {
	     this.password = password;
	}
	public String getAccount() {
	     return account;
	}
	public void setAccount(String account) {
	     this.account = account;
	}
	public Integer getDivisionId() {
	     return divisionId;
	}
	public void setDivisionId(Integer divisionId) {
	     this.divisionId = divisionId;
	}

	public Date getCreatedDate() {
		return created_date;
	}

	public void setCreatedDate(Date created_date) {
		this.created_date = created_date;
	}

	public Date getupdatedDate() {
		return updated_date;
	}

	public void setUpdatedDate(Date updated_date) {
		this.updated_date = updated_date;
	}
	public Integer getProgress() {
	     return progress;
	}
	public void setProgress(Integer progress) {
	     this.progress = progress;
	}

}

src/main/java/jp/co/elearning/form/SettingForm.java
package jp.co.elearning.form;

import javax.validation.constraints.Pattern;

public class SettingForm {
	private Integer id;
	private int divisionId;

	@Pattern(message = "パスワードは記号を含む、全ての半角英数字で、6文字から20文字で入力してください", regexp = "^[-_@+*;:#$%&A-Za-z0-9]{8,20}$")
	private String password;

	private String passwordConfirm;

	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public int getDivisionId() {
		return divisionId;
	}
	public void setDivisionId(int divisionId) {
		this.divisionId = divisionId;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getPasswordConfirm() {
	     return passwordConfirm;
	}
	public void setPasswordConfirm(String passwordConfirm) {
	     this.passwordConfirm = passwordConfirm;
	}

}

src/main/java/jp/co/elearning/controller/HomeController.java
package jp.co.elearning.controller;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import jp.co.elearning.dto.UserDto;
import jp.co.elearning.form.UserForm;
import jp.co.elearning.service.LoginService;


@Controller
public class HomeController {


	/*@Autowired
	private LoginService loginService;*/

	@Autowired
	HttpSession session;
	@Autowired
	HttpServletRequest request;
	@Autowired
	private LoginService loginService;

	@RequestMapping(value = "/home", method = RequestMethod.GET)
	public String loginUser(@ModelAttribute UserForm form, Model model) {
		UserDto dto = (UserDto) session.getAttribute("loginUser");
		Integer userId = dto.getId();
		UserDto user = loginService.selectUserProgress(userId);
		model.addAttribute("user", user);
		return "home";
	}

}

src/main/java/jp/co/elearning/controller/LoginController.java
package jp.co.elearning.controller;

import javax.servlet.http.HttpSession;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import jp.co.elearning.dto.UserDto;
import jp.co.elearning.form.LoginForm;
import jp.co.elearning.service.LoginService;

@Controller
public class LoginController {
	@Autowired
	HttpSession session;
	@Autowired
	private LoginService loginService;

	@RequestMapping(value = "/login", method = RequestMethod.GET)
	public String showMessage(Model model) {
		model.addAttribute("message", "ログインしてください");
		return "login";
	}

	@RequestMapping(value = "/login", method = RequestMethod.POST)
	public String login(@Valid @ModelAttribute LoginForm form, BindingResult result, Model model) {
		String password = form.getPassword();
		UserDto loginUser = loginService.getUser(form);
		String account = form.getAccount();

		if (loginUser == null) {
			model.addAttribute("account",account);
			model.addAttribute("message", "ログインに失敗しました");
			return "login";

		}else if(password.matches("[0-9]{7}")) {

			String str = "redirect:/setting/" + loginUser.getId();
			session.setAttribute("passwordMessage", "パスワードを変更してください");
			session.setAttribute("loginUser", loginUser);
			return str;
		}

		session.setAttribute("loginUser", loginUser);
		return "redirect:/home";
	}
}

src/main/java/jp/co/elearning/controller/ManagementController.java
package jp.co.elearning.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import jp.co.elearning.dto.UserDto;
import jp.co.elearning.form.SettingForm;
import jp.co.elearning.service.LoginService;

@Controller
public class ManagementController {
	@Autowired
	private LoginService loginService;

	@RequestMapping(value = "/management", method = RequestMethod.GET)
	public String allUsers(Model model) {
		List<UserDto> users = loginService.getAllUsers();
		model.addAttribute("users", users);
		return "management";
	}

	@RequestMapping(value = "/management", method = RequestMethod.POST)
	public String postManagement(@ModelAttribute SettingForm form, Model model) {
		model.addAttribute("settingForm", form);
		return "redirect:/setting/{id}";
	}
}

src/main/java/jp/co/elearning/controller/SettingController.java
package jp.co.elearning.controller;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.util.StringUtils;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import jp.co.elearning.dto.UserDto;
import jp.co.elearning.dto.UserIdDto;
import jp.co.elearning.entity.User;
import jp.co.elearning.form.SettingForm;
import jp.co.elearning.service.LoginService;
import jp.co.elearning.service.SettingService;

@Controller
public class SettingController {

	@Autowired
	private SettingService settingService;

	@Autowired
	private LoginService loginService;

	@Autowired
	HttpSession session;

	@Autowired
	HttpServletRequest request;

	@RequestMapping(value = "/setting/{id}", method = RequestMethod.GET)
	public String selectUser(Model model, @PathVariable ("id") String id) {

		UserDto userDto = (UserDto) session.getAttribute("loginUser");
		Integer userId = userDto.getId();
		UserDto user = loginService.selectUserProgress(userId);
		model.addAttribute("user", user);
		UserIdDto dto = new UserIdDto();
		dto.setId(id);

		if (!id.matches("^[0-9]+$") || id.isEmpty()) {
			model.addAttribute("errorMessages", "不正なパラメーターが入力されました");
			return "home";
		}else {
			UserDto checkUser = settingService.selectUser(Integer.parseInt(dto.getId()));
			model.addAttribute("checkUser", checkUser);
			if(checkUser == null) {
				model.addAttribute("errorMessages", "不正なパラメーターが入力されました");
				return "home";
			}
		}
		return "setting";
	}

	@RequestMapping(value = "/setting/{id}", method = RequestMethod.POST)
	public String userUpdate(@Valid @ModelAttribute SettingForm form, BindingResult result, User user, Model model) {

		if(StringUtils.isEmpty(form.getPassword()) && form.getDivisionId() == 0) {
			session.setAttribute("validation", "パスワードは記号を含む、全ての半角英数字で、8文字から20文字で入力してください");
			return "redirect:/setting/{id}";
		}

		if(result.hasErrors()) {
			session.setAttribute("validation", "パスワードは記号を含む、全ての半角英数字で、8文字から20文字で入力してください");
			session.setAttribute("errorMessages", "パスワードと確認用パスワードが一致していません");
			model.addAttribute("settingForm", form);
			return "redirect:/setting/{id}";
		}

		if(StringUtils.isEmpty(form.getPassword())) {
			settingService.updateDivisionId(form);
			model.addAttribute("settingForm", form);
			return "redirect:/home";
		}else if(form.getDivisionId() == 0) {
			if(result.hasErrors()) {
				session.setAttribute("validation", "パスワードは記号を含む、全ての半角英数字で、8文字から20文字で入力してください");
				session.setAttribute("errorMessages", "パスワードと確認用パスワードが一致していません");
				model.addAttribute("settingForm", form);
				return "redirect:/setting/{id}";
			} else {
				if(!form.getPassword().equals(form.getPasswordConfirm())) {
					session.setAttribute("errorMessages", "パスワードと確認用パスワードが一致していません");
					return "redirect:/setting/{id}";
				}
			settingService.updatePassword(form);
			model.addAttribute("settingForm", form);

			}
		}
		return "redirect:/home";
	}
}

src/main/java/jp/co/elearning/controller/SignUpController.java
package jp.co.elearning.controller;

import javax.validation.Valid;

import org.jboss.logging.Logger;
import org.jboss.logging.Logger.Level;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import jp.co.elearning.dto.UserDto;
import jp.co.elearning.form.UserForm;
import jp.co.elearning.service.SignUpService;

@Controller
public class SignUpController {

	@Autowired
	private SignUpService signUpService;

	@RequestMapping(value = "/signup", method = RequestMethod.GET)
	public String user(Model model) {

		//model.addAttribute("message", "新規登録");
		return "signup";
	}

	@RequestMapping(value = "/signup", method = RequestMethod.POST)
	public String userInsert(@Valid @ModelAttribute UserForm form, BindingResult result, Model model) {

		if(result.hasErrors()) {
			model.addAttribute("message", "新規登録");
			model.addAttribute("account", form.getAccount());
			model.addAttribute("name", form.getName());
			return "signup";
		}

		UserDto user = signUpService.selectOldUser(form);

		if(user != null) {
			model.addAttribute("account", form.getAccount());
			model.addAttribute("name", form.getName());
			model.addAttribute("errorMessages", "アカウントが重複しています");
			return "signup";
		}

		if(!form.getPassword().equals(form.getPasswordConfirm())) {
			model.addAttribute("account", form.getAccount());
			model.addAttribute("name", form.getName());
			model.addAttribute("message", "以下のエラーを解消してください");
			model.addAttribute("errorMessages", "パスワードと確認用パスワードが一致していません");
			return "signup";
		}
		int count = signUpService.insertUser(form);
		model.addAttribute("userForm", form);
		Logger.getLogger(SignUpController.class).log(Level.INFO, "挿入件数は" + count + "件です。");
		return "redirect:/home";
	}
}

src/main/webapp/WEB-INF/view/confirm.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@page isELIgnored="false"%>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>送信前確認画面</title>
		 <link href="<c:url value="/resources/css/style.css" />" rel="stylesheet" >
	</head>
	<body>
		<a href="/ELearningTeam/home"><img src="https://www.alhinc.jp/img/common/h-logo.svg" width="150" height="100"></a>
		<div class="main-contents">
		<h1>送信前確認画面</h1>
		<form:form modelAttribute="questionForm" action="result" method="get">

			<div class="confirm-question" title="問1">
			<c:out value="${question1}" /><br /><br/>
			</div>
			<div class="selected-answer" title="あなたが選んだ答え">
			<c:out value="${choice1}" /><br />
			</div>

			<div class="confirm-question" title="問2">
			<c:out value="${question2}" /><br /><br/>
			</div>
			<div class="selected-answer" title="あなたが選んだ答え">
			<c:out value="${choice2}" /><br />
			</div>

			<div class="confirm-question" title="問3">
			<c:out value="${question3}" /><br /><br/>
			</div>
			<div class="selected-answer" title="あなたが選んだ答え">
			<c:out value="${choice3}" /><br />
			</div>

			<div class="confirm-question" title="問4">
			<c:out value="${question4}" /><br /><br/>
			</div>
			<div class="selected-answer" title="あなたが選んだ答え">
			<c:out value="${choice4}" /><br />
			</div>

			<div class="confirm-question" title="問5">
			<c:out value="${question5}" /><br /><br/>
			</div>
			<div class="selected-answer" title="あなたが選んだ答え">
			<c:out value="${choice5}" /><br />
			</div>

			<div class="confirm-question" title="問6">
			<c:out value="${question6}" /><br /><br/>
			</div>
			<div class="selected-answer" title="あなたが選んだ答え">
			<c:out value="${choice6}" /><br />
			</div>

			<div class="confirm-question" title="問7">
			<c:out value="${question7}" /><br /><br/>
			</div>
			<div class="selected-answer" title="あなたが選んだ答え">
			<c:out value="${choice7}" /><br />
			</div>

			<div class="confirm-question" title="問8">
			<c:out value="${question8}" /><br /><br/>
			</div>
			<div class="selected-answer" title="あなたが選んだ答え">
			<c:out value="${choice8}" /><br />
			</div>

			<div class="confirm-question" title="問9">
			<c:out value="${question9}" /><br /><br/>
			</div>
			<div class="selected-answer" title="あなたが選んだ答え">
			<c:out value="${choice9}" /><br />
			</div>

			<div class="confirm-question" title="問10">
			<c:out value="${question10}" /><br /><br/>
			</div>
			<div class="selected-answer" title="あなたが選んだ答え">
			<c:out value="${choice10}" /><br />
			</div>

		<input name = "userProgress" id = "userProgress" value = "${userProgress}" type = "hidden"><br />

			<input type = "submit" value = "送信" class="button">
		</form:form>
		<form:form modelAttribute = "resultForm">
			 <a href="javascript:void(0)" onclick="javascript:history.back()" class="button">回答を修正する</a>
		</form:form><br /><br />
		<div class="copyright">Copyright(C)西宮原庄</div>
		</div>
	</body>
</html>

src/main/webapp/WEB-INF/view/home.jsp
<!DOCTYPE html>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<html>
<head>
<meta charset="UTF-8">
<title>ELearning</title>
        <link href="<c:url value="/resources/css/style.css" />" rel="stylesheet" >

</head>
<body>
	<a href="/ELearningTeam/home"><img src="https://www.alhinc.jp/img/common/h-logo.svg" width="150" height="100"></a>
	<c:remove var = "answer1" scope = "session"/>
	<c:remove var = "answer2" scope = "session"/>
	<c:remove var = "answer3" scope = "session"/>
	<c:remove var = "answer4" scope = "session"/>
	<c:remove var = "answer5" scope = "session"/>
	<c:remove var = "answer6" scope = "session"/>
	<c:remove var = "answer7" scope = "session"/>
	<c:remove var = "answer8" scope = "session"/>
	<c:remove var = "answer9" scope = "session"/>
	<c:remove var = "answer10" scope = "session"/>
	<c:remove var = "errorMessages" scope = "session"/>
	<c:remove var = "checkUser" scope = "session"/>
	<c:remove var = "validation" scope = "session"/>

	<div class="main-contents">
		<h1>ようこそ${loginUser.name}さん</h1>
		<h1>ホーム画面</h1>
		<div class="header">
			<form:form action="{logout}" method="post">

				<a href="/ELearningTeam/login" class="button">ログアウト</a>
			</form:form>
			<form:form modelAttribute="userForm" action="/ELearningTeam/home">
				<input type = "hidden" value="${loginUser.id}" name = "id" id = "id">
			</form:form>
			<c:if test="${loginUser.divisionId==1}">
				<a href="/ELearningTeam/management/" class="button">ユーザー一覧</a>
			</c:if>
			<c:if test="${loginUser.divisionId==2}">
				<a href="/ELearningTeam/setting/${loginUser.id}" class="button">パスワード変更</a>
			</c:if>
			<br />
			<div class="homeprogress">
			<br/><br/>
			<c:out value = "${errorMessages}"></c:out>
			<br /><br/>
			受験状況:
			<c:if test="${user.progress==0}"><span class="progress">未受験</span></c:if>
			<c:if test="${user.progress==1}"><span class="progress">不合格</span></c:if>
			<c:if test="${user.progress==2}"><span class="progress">合格</span></c:if>
			</div>
		</div>
		<div class="contents">
			<button onclick="location.href='/ELearningTeam/question1'" class="button">問題スタート</button>
		</div><br /><br />
		<div class="copyright">Copyright(C)西宮原庄</div>
	</div>
</body>
</html>

src/main/webapp/WEB-INF/view/login.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>ログイン画面</title>
		<link href="<c:url value="/resources/css/style.css" />" rel="stylesheet" >
	</head>
	<body>
		<a href="/ELearningTeam/home"><img src="https://www.alhinc.jp/img/common/h-logo.svg" width="150" height="100"></a>
		<div class="main-contents">
			<h1>${message}</h1>

			<c:remove var = "loginUser" scope = "session"/>

			<form:form modelAttribute="loginForm">
			<div>
				<form:errors path="*" />
			</div>
			アカウント名：<input type="text" id="account" name="account" value = "<c:out value="${ account }"/>"><br/>

			パスワード：<input type="password" class="field" id="password" name="password"><br/>
			<input type="checkbox" id="password-check">パスワードを表示する<br/>
			<input type="submit" value="ログイン" class="button">
			<script>
 				const pwd = document.getElementById('password');
 				const pwdCheck = document.getElementById('password-check');
 				pwdCheck.addEventListener('change', function() {
     				if(pwdCheck.checked) {
         				pwd.setAttribute('type', 'text');
     				} else {
         				pwd.setAttribute('type', 'password');
     				}
 				}, false);
 			</script>
			</form:form><br /><br />
			<div class="copyright">Copyright(C)西宮原庄</div>
		</div>
	</body>
</html>

src/main/webapp/WEB-INF/view/management.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>ユーザー一覧</title>
        <link href="<c:url value="/resources/css/style.css" />" rel="stylesheet" >
</head>
<body>
	<a href="/ELearningTeam/home"><img src="https://www.alhinc.jp/img/common/h-logo.svg" width="150" height="100"></a>
	<div class="main-contents">
		<a href="/ELearningTeam/home" class="button">ホーム</a>
		<a href="/ELearningTeam/signup" class="button">新規登録</a>
		<h1>ユーザー一覧</h1>
		<div class="container">
			<c:forEach items="${users}" var="user">
				<div class="userlist">
					<form:form modelAttribute="settingForm">
						<input type="hidden" name="id" value="${user.id}" id="id" />
						アカウント名: <c:out value="${user.account}" /><br />
						氏名: <c:out value="${user.name }" /><br />
						所属: <c:if test="${user.divisionId==1 }">WBU</c:if>
						<c:if test="${user.divisionId==2 }">受験者</c:if><br />
						受験状況: <c:if test="${user.progress==0}">未受験</c:if>
						<c:if test="${user.progress==1}">不合格</c:if>
						<c:if test="${user.progress==2}">合格</c:if><br />
						作成日: <c:out value="${user.createdDate }" /><br />
						最終更新日: <c:out value="${user.updatedDate }" /><br />
						<a href="/ELearningTeam/setting/${user.id}" class="button">編集</a>
					</form:form>
				</div>
			</c:forEach>
			<br /><br />
			<div class="copyright">Copyright(C)西宮原庄</div>
		</div>
	</div>
</body>
</html>

src/main/webapp/WEB-INF/view/question1.jsp
<!DOCTYPE html>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<html>
	<head>
	    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	    <title>セキュリティ問題</title>
	     <link href="<c:url value="/resources/css/style.css" />" rel="stylesheet" >
	</head>
	<body>
	<a href="/ELearningTeam/home"><img src="https://www.alhinc.jp/img/common/h-logo.svg" width="150" height="100"></a>
		<div class="main-contents">
		    <h1>セキュリティ問題</h1>

		    <form:form modelAttribute="questionForm" action="confirm" method="get" >
		        <div class="question" title="問1"><c:out value="${question1}" /></div><br />
		        <div class="choice"><form:radiobuttons path="choiceText1" delimiter="<br>" items="${choices40}" /></div><br /><br />

		        <div class="question" title="問2"><c:out value="${question2}" /></div><br />
		        <div class="choice"><form:radiobuttons path="choiceText2" delimiter="<br>" items="${choices41}" /></div><br /><br />

		        <div class="question" title="問3"><c:out value="${question3}" /></div><br />
		        <div class="choice"><form:radiobuttons path="choiceText3" delimiter="<br>" items="${choices42}" /></div><br /><br />

		        <div class="question" title="問4"><c:out value="${question4}" /></div><br />
		        <div class="choice"><form:radiobuttons path="choiceText4" delimiter="<br>" items="${choices43}" /></div><br /><br />

		        <div class="question" title="問5"><c:out value="${question5}" /></div><br />
		      	<div class="choice"><form:radiobuttons path="choiceText5" delimiter="<br>" items="${choices44}" /></div><br /><br />

		        <div class="question" title="問6"><c:out value="${question6}" /></div><br />
		        <div class="choice"><form:radiobuttons path="choiceText6" delimiter="<br>" items="${choices45}" /></div><br /><br />

		        <div class="question" title="問7"><c:out value="${question7}" /></div><br />
		        <div class="choice"><form:radiobuttons path="choiceText7" delimiter="<br>" items="${choices46}" /></div><br /><br />

		        <div class="question" title="問8"><c:out value="${question8}" /></div><br />
		        <div class="choice"><form:radiobuttons path="choiceText8" delimiter="<br>" items="${choices47}" /></div><br /><br />

		        <div class="question" title="問9"><c:out value="${question9}" /></div><br />
		        <div class="choice"><form:radiobuttons path="choiceText9" delimiter="<br>" items="${choices48}" /></div><br /><br />

		        <div class="question" title="問10"><c:out value="${question10}" /></div><br />
		       <div class="choice"> <form:radiobuttons path="choiceText10" delimiter="<br>" items="${choices49}" /></div><br /><br />
		        <input type="submit" value="送信" class="button" /><br />
			</form:form>
			<div class="copyright">Copyright(C)西宮原庄</div>
		</div>
	</body>
</html>

src/main/webapp/WEB-INF/view/showMessage.jsp
<!DOCTYPE html>

<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
    
<html>
	<head>
		<meta charset="utf-8">
		<title>Welcome</title>
	</head> 
	<body>
		<h2>${message}</h2>
	</body>
</html>